/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dce2f3",
        "secondary": "#5d5f5d",
        "primary-container": "#1c2d24",
        "outline": "#737874",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#454745",
        "on-secondary-container": "#636563",
        "outline-variant": "#c3c8c2",
        "primary": "#071810",
        "surface": "#f9f9ff",
        "on-surface": "#151c27",
        "tertiary-fixed": "#e3e3de",
        "secondary-fixed-dim": "#c6c7c4",
        "on-surface-variant": "#434844",
        "surface-bright": "#f9f9ff",
        "secondary-fixed": "#e2e3e0",
        "tertiary-fixed-dim": "#c6c7c2",
        "inverse-on-surface": "#ebf1ff",
        "secondary-container": "#e2e3e0",
        "on-primary": "#ffffff",
        "background": "#f9f9ff",
        "surface-container-high": "#e2e8f8",
        "on-tertiary-fixed-variant": "#464744",
        "on-tertiary-fixed": "#1a1c19",
        "surface-container": "#e7eefe",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed": "#0e1f17",
        "inverse-primary": "#b7cbbe",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-dim": "#d3daea",
        "tertiary-container": "#282a27",
        "primary-fixed": "#d3e7da",
        "inverse-surface": "#2a313d",
        "on-background": "#151c27",
        "on-primary-container": "#829589",
        "on-tertiary-container": "#90918d",
        "on-primary-fixed-variant": "#394b41",
        "tertiary": "#141613",
        "on-secondary": "#ffffff",
        "surface-tint": "#506358",
        "surface-container-highest": "#dce2f3",
        "primary-fixed-dim": "#b7cbbe",
        "on-secondary-fixed": "#1a1c1b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "container-max-width": "1440px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display"],
        "body-md": ["Outfit"],
        "headline-lg": ["Playfair Display"],
        "data-tabular": ["Outfit"],
        "display-lg": ["Playfair Display"],
        "label-md": ["Outfit"],
        "label-sm": ["Outfit"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Outfit"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "data-tabular": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
