# Generated by Django 5.2.14 on 2026-05-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_facility',
            },
        ),
        migrations.CreateModel(
            name='RawIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Fuel & Procurement'), ('UTILITY', 'Utility Portal Electricity'), ('TRAVEL', 'Corporate Travel flights')], max_length=50)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_ingestion_log',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'core_tenant',
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_icon', models.CharField(default='database', max_length=100)),
                ('ingest_date', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=50)),
                ('raw_value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(default='N/A', max_length=255)),
                ('calc_emissions', models.FloatField()),
                ('status', models.CharField(choices=[('Approved', 'Approved & Locked'), ('Suspicious', 'Flagged as Suspicious'), ('Failed', 'Processing Failed')], default='Suspicious', max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.facility')),
                ('raw_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.rawingestionlog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.tenant')),
            ],
            options={
                'db_table': 'core_normalized_record',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('user', models.CharField(default='Sai Ganesh', max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.normalizedrecord')),
            ],
            options={
                'db_table': 'core_audit_trail',
            },
        ),
        migrations.AddField(
            model_name='rawingestionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'code')},
        ),
    ]
