# Generated by Django 5.2.14 on 2026-05-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawingestionlog',
            name='raw_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
