# Generated by Django 5.2.14 on 2026-05-28 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rawingestionlog_raw_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittrail',
            old_name='action',
            new_name='action_taken',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='time',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='user',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='delta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user_id',
            field=models.CharField(default='system', max_length=255),
        ),
    ]
